hospitalmanagement/hospital/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns =[
    path('', views.homebase, name='homebase'),
    path('home', views.home, name='home'),
    path('aboutus', views.aboutus, name='aboutus'),#name is use to swith btw html using this key name valu(html) will be returned
    path('contact', views.contact, name='contact'),
    path('contact/submit/', views.contact_submit, name='contact_submit'),
    path('departments', views.departments, name='departments'),
    path('doctors', views.doctors, name='doctors'),
    path('services',views.services, name='services'),
    path('book/', views.book, name='book'),


    path('admin_panel/billings/edit/<int:pk>/', views.admin_edit_billing, name='admin_edit_billing'),
    #for admin#
    path('add_doctor/', views.add_doctor, name='add_doctor'),
    path('doctors/', views.admin_doctor_list, name='admin_doctor_list'),
    path('edit_doctor/<int:doctor_id>/', views.admin_edit_doctor, name='admin_edit_doctor'),


#     ###  from dashboard app ####
# # Dashboard related views
    path('dashboard_home/', views.dashboard_home, name='dashboard_home'),



    path('departments/', views.department_list, name='department_list'),
    path('departments/add/', views.add_department, name='add_department'),

    path('departments/edit/<int:pk>/', views.edit_department, name='edit_department'),


#     # path('adminsignup/', views.adminsignup, name='adminsignup'),
#     # path('adminlogin/', views.adminlogin, name='adminlogin'),
#     # path('doctorsignup/', views.doctorsignup, name='doctorsignup'),
#     # path('doctorlogin/', views.doctorlogin, name='doctorlogin'),
#     # path('patientsignup/', views.patientsignup, name='patientsignup'),
#     # path('patientlogin/', views.patientlogin, name='patientlogin'),
#     # path('patientindex/', views.patientindex, name='patientindex'),
#
#     path('admin_signup/', views.admin_signup_view, name='admin_signup'),
#     # path('admin_login/', LoginView.as_view(template_name='dashboard/admin_login.html'), name='admin_login'),
#
#     ### patient ###
#     path('register/patient/', views.patient_register, name='patient_register'),
#     path('login/patient/', views.patient_login, name='patient_login'),
#     path("dashboard/patient/", views.patient_dashboard, name="patient_dashboard"),
#
#     ### doctor ###
#     path('register/doctor/', views.doctor_register, name='doctor_register'),
#     path('login/doctor/', views.doctor_login, name='doctor_login'),
#     path("dashboard/doctor/", views.doctor_dashboard, name="doctor_dashboard"),
#
#     ### admin_panel ###
#     path('register/admin_panel/', views.admin_register, name='admin_register'),
#     path('login/admin_panel/', views.admin_login, name='admin_login'),
#     path("dashboard/admin_panel/", views.admin_dashboard, name="admin_dashboard"),
#
#
# # Logout view
#     # path('register/', views.register, name='register'),
#     # path('login/', views.login_view, name="login"),
#     # path("logout/", auth_views.LogoutView.as_view(), name="logout"),
#     path('logout/', views.logout_view, name='logout'),
#
#
#
#
#
# # CRUD operations
#     path('patients/', views.patient_list, name='patient_list'),
#     # path('patient/book_appointment/', views.book_appointment, name='book_appointment'),
#     path('patients/add/', views.add_patient, name="add_patient"),
#     path('patients/edit/<int:pk>/', views.edit_patient, name="edit_patient"),
#     path('doctors/', views.doctor_list, name="doctor_list"),
#     path("doctors/add/", views.add_doctor, name="add_doctor"),
#     path("doctors/edit/<int:pk>/", views.edit_doctor, name="edit_doctor"),
#     path("billings/", views.billing_list, name="billing_list"),
#     path("billings/add/", views.add_billing, name="add_billing"),
#     path("report/", views.report, name='report'),
#
#
# # Admin admin_panel views
#     ####admin_panel####
# #add,edit of patient,doctor,billing
#     path("admin_panel/", views.admin_dashboard, name="admin_dashboard"),
#     path('admin_panel/patients/', views.admin_patient_list, name='admin_patient_list'),
#     path('admin_panel/patients/add/', views.admin_add_patient, name='admin_add_patient'),
#     path('admin_panel/patients/edit/<int:pk>/', views.admin_edit_patient, name="admin_edit_patient"),
#     path("admin_panel/doctors/", views.admin_doctor_list, name='admin_doctor_list'),
#     path("admin_panel/doctors/add/", views.admin_add_doctor, name='admin_add_doctor'),
#     path('admin_panel/doctors/edit/<int:pk>/', views.admin_edit_doctor, name="admin_edit_doctor"),
#     path('admin_panel/billings/', views.admin_billing_list, name="admin_billing_list"),
#     path("admin_panel/billings/add", views.admin_add_billing, name="admin_add_billing"),
#     path("admin_panel/billings/edit/<int:pk>/", views.admin_edit_billing, name="admin_edit_billing"),

# Custom admin admin_panel view
#     path("index/", views.panel_index, name="panel_index"),
]

hospitalmanagement/hospitalmanagement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



if settings.DEBUG:
    urlpatterns = [
        path("admin/", admin.site.urls),  # Default Django admin URL
        path("admin_custom/", include('hospital.admin_urls')),  # Custom admin admin_panel URLs
        path("patient/", include('hospital.patient_urls')),
        path("doctor/", include('hospital.doctor_urls')),
        path('', include('hospital.urls')),
        path('accounts/', include('django.contrib.auth.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hospitalmanagement/hospital/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.utils import timezone
from django.contrib.auth.hashers import make_password


# Create your models here.

class Department(models.Model):
    # objects = None
    dep_name = models.CharField(max_length=100)
    dep_description = models.TextField()

    def __str__(self):
        return self.dep_name


# class Doctors(models.Model):
#     #
#
#     #
#     doc_name = models.CharField(max_length=255)
#     doc_spec = models.CharField(max_length=255)
#     dep_name = models.ForeignKey(Department, on_delete=models.CASCADE)
#     doc_image = models.ImageField(upload_to='doctors')
#     def __str__(self):
#         return self.doc_name


# from django.db import models
#
# class Department(models.Model):
#     dep_name = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.dep_name

# class Doctor(models.Model):
#     first_name = models.CharField(max_length=100)
#     last_name = models.CharField(max_length=100)
#     email = models.EmailField()
#     contact = models.CharField(max_length=15)
#     department = models.ForeignKey(Department, on_delete=models.CASCADE)
#     doc_spec = models.CharField(max_length=255)
#     availability = models.CharField(max_length=10)
#     doc_image = models.ImageField(upload_to='doctors/', null=True, blank=True)
#     date_joined = models.DateField(auto_now_add=True)
#     new_department_name = models.CharField(max_length=100, blank=True)
#
#     def __str__(self):
#         return f"{self.first_name} {self.last_name}"


######### from dash board app #########
class Profile(models.Model):
    USER_TYPE_CHOICES = [
        ('admin_panel', 'Admin'),
        ('doctor', 'Doctor'),
        ('patient', 'Patient'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=50, choices=USER_TYPE_CHOICES, default='patient')


# class Patient(models.Model):
#     first_name = models.CharField(max_length=50, default='')
#     last_name = models.CharField(max_length=50, default='')
#     email = models.EmailField(unique=True, default='')
#     contact = models.CharField(max_length=15)
#     password = models.CharField(max_length=128, default='')
#
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#
#
#     date_of_birth = models.DateField(default=timezone.now)
#     address = models.TextField(default='')
#     gender = models.CharField(max_length=10, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')],
#                               default='Male')
#     medical_history = models.TextField(blank=True)
#     date_created = models.DateTimeField(default=timezone.now)
#     date_updated = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return f"{self.first_name} {self.last_name}"




# class Patient(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=50)
#     last_name = models.CharField(max_length=50)
#     email = models.EmailField(unique=True)
#     contact = models.CharField(max_length=15)
#     password = models.CharField(max_length=128)
#     date_of_birth = models.DateField()
#     address = models.TextField()
#     GENDER_CHOICES = [
#         ('Male', 'Male'),
#         ('Female', 'Female'),
#         ('Other', 'Other'),
#     ]
#     gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='Male')
#     medical_history = models.TextField(blank=True)
#     date_created = models.DateTimeField(default=timezone.now)
#     date_updated = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return f"{self.first_name} {self.last_name}"


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, default='')
    last_name = models.CharField(max_length=50, default='')
    email = models.EmailField(unique=True, default='')
    contact = models.CharField(max_length=15)
    date_of_birth = models.DateField(default=timezone.now)
    address = models.TextField(default='')
    gender = models.CharField(max_length=10, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male')
    medical_history = models.TextField(blank=True)
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


# class Doctor(models.Model):
#     DEPARTMENT_CHOICES = [
#         ('Cardiology', 'Cardiology'),
#         ('Neurology', 'Neurology'),
#         ('Pediatrics', 'Pediatrics'),
#         ('Orthopedics', 'Orthopedics'),
#         ('General', 'General'),
#     ]
#
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=50, default='')
#     last_name = models.CharField(max_length=50, default='')
#     email = models.EmailField(unique=True, default='')
#     contact = models.CharField(max_length=15, default='')
#     department = models.CharField(max_length=50, choices=DEPARTMENT_CHOICES, default='General')
#     availability = models.CharField(max_length=50, default='Unknown')
#     date_joined = models.DateField(auto_now_add=True)
#     date_created = models.DateTimeField(auto_now_add=True)
#     date_updated = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return f"Dr. {self.first_name} {self.last_name} - ({self.department})"
#


# class Doctor(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=50)
#     last_name = models.CharField(max_length=50)
#     email = models.EmailField(unique=True)
#     contact = models.CharField(max_length=15)
#     department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)
#     new_department_name = models.CharField(max_length=100, blank=True)
#     doc_spec = models.CharField(max_length=255)
#     availability = models.CharField(max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')], default='')
#     date_joined = models.DateField(auto_now_add=True)
#     date_created = models.DateTimeField(auto_now_add=True)
#     date_updated = models.DateTimeField(auto_now=True)
#     doc_image = models.ImageField(upload_to='doctors', blank=True, null=True)
#
#     def __str__(self):
#         return f"Dr. {self.first_name} {self.last_name} - ({self.department or self.new_department_name})"


# latest
# class Doctor(models.Model):
#
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#
#     first_name = models.CharField(max_length=100)
#     last_name = models.CharField(max_length=100)
#     email = models.EmailField(unique=True)
#     contact = models.CharField(max_length=15)
#     department = models.ForeignKey(Department, on_delete=models.CASCADE)
#     # new_department_name = models.CharField(max_length=100, blank=True)
#
#     doc_spec = models.CharField(max_length=255)
#     availability = models.CharField(max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes')
#     doc_image = models.ImageField(upload_to='doctors', blank=True, null=True)
#     date_joined = models.DateField(auto_now_add=True)
#
#     # class Meta:
#     #     # This will tell Django to create and manage the database table for this model
#     #     managed = True
#
#     def __str__(self):
#         return f"{self.first_name} {self.last_name} - ({self.department.name})"
#
#     class Meta:
#         verbose_name = "Doctor"
#         verbose_name_plural = "Doctors"


class Doctor(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='doctor')

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    contact = models.CharField(max_length=15)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    doc_spec = models.CharField(max_length=255)
    availability = models.CharField(max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes')
    doc_image = models.ImageField(upload_to='doctors', blank=True, null=True)
    date_joined = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - ({self.department.dep_name})"

    class Meta:
        verbose_name = "Doctor"
        verbose_name_plural = "Doctors"


class Admin(models.Model):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=128)

    def __str__(self):
        return self.username


class DoctorProfile(models.Model):
    doctor = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=255)

    def __str__(self):
        return f"Dr. {self.user.get_full_name()} ({self.department})"


# class Appointment(models.Model):
#     patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name="appointments_as_patient")
#     doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="appointments_as_doctor")
#     doctor_department = models.CharField(max_length=255, default='General')
#     date = models.DateField()
#     time = models.TimeField()
#     symptoms = models.TextField(blank=True, null=True)
#
#     def __str__(self):
#         return f"{self.patient.username} with {self.doctor.username} - ({self.doctor_department}) on {self.date} at {self.time}"


class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name="appointments_as_patient")
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="appointments_as_doctor")
    date = models.DateField()

hospitalmanagement/hospital/templates/patient/login_patient.html
<!DOCTYPE html>
{% include 'dashboard/inline_css.html' %}

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Login</title>
</head>
<body>
<header>
   <div class="header-bottom" data-header>
      <div class="container">
         <a href="{% url 'homebase' %}" class="logo">Medico</a>
      </div>
   </div>
</header>
    <div class="form-container">
        <form method="post" class="form">
            {% csrf_token %}
            <h2 class="form-title">Patient Login</h2>

            {% if error %}
            <p class="error" style="color: red;">{{ error }}</p>
            {% endif %}

            <label for="email" class="label">Email:</label>
            <input type="email" id="email" name="email" class="input" required>

            <label for="password" class="label">Password:</label>
            <input type="password" id="password" name="password" class="input" required>

            <button type="submit" class="btn btn-primary">Login</button>
            <br>
            <div class="text-center">Don't have an account? <a href="{% url 'patient_register' %}" class="blue-link">Signup here</a></div>
            <div style="margin-top:10px;"><button onclick="window.history.back()" class="btn btn-primary">Go Back</button></div>
        </form>
    </div>
</body>
</html>

hospitalmanagement/hospital/templates/patient/patient_appointment_list.html
{% include 'patient/patient_navbar.html' %}

{% block content %}
<section class="section patient" id="appointments" aria-label="appointments" style="margin-bottom: 10px;">
  <div class="container">
    <div class="dashboard-card" style="box-shadow: var(--shadow-4); margin-bottom: 20px; padding: 30px; border: 1px solid var(--light-gray); border-radius: var(--radius-6); text-align: left; transition: transform 0.3s ease, box-shadow 0.3s ease;">
      <p class="section-subtitle text-center">Patient Dashboard</p>
      <h2 class="h2 section-title text-center">Your Appointments</h2>
      <br><br>
      <ul class="list-group">
        {% for appointment in appointments %}
        <li class="list-group-item">
          <strong style="color:black;">Doctor:</strong> Dr. {{ appointment.doctor.user.first_name }} {{ appointment.doctor.user.last_name }} - ({{ appointment.doctor.department.dep_name }} Department)<br>
          <strong style="color:black;">Date:</strong> {{ appointment.date }}<br>
          <strong style="color:black;">Time:</strong> {{ appointment.time }}<br>
          <strong style="color:black;">Symptoms:</strong> {{ appointment.symptoms }}<br><br>
          <a href="{% url 'patient_delete_appointment' appointment.id %}" class="btn btn-danger btn-sm float-right">Delete</a>
          <br><br>
          <a href="{% url 'patient_edit_appointment' appointment.id %}" class="btn btn-primary btn-sm float-right mr-2">Edit</a>
        </li>
        <br><br><br>
        {% empty %}
        <li class="list-group-item list-group-item-warning">No appointments scheduled.</li>
        {% endfor %}
      </ul>

    </div>
  </div>
</section>

{% endblock %}

hospitalmanagement/hospital/templates/patient/patient_book_appointment.html
{% include 'patient/patient_navbar.html' %}

{% block content %}
<section class="section dashboard" id="dashboard" aria-label="dashboard" style="margin-bottom: 10px; width: 100%; background-size: cover; background-repeat: no-repeat; background-position: center center;">
  <div class="container">
    <div class="dashboard-card" style="box-shadow: var(--shadow-4); margin-bottom: 20px; padding: 30px; border: 1px solid var(--light-gray); border-radius: var(--radius-6); text-align: center; transition: transform 0.3s ease, box-shadow 0.3s ease;">
      <p class="section-subtitle text-center">Patient Dashboard</p>
      <h2 class="h2 section-title text-center">Book an Appointment</h2>
    </div>
  </div>
  <br><br><br>

  <div class="container">
    <div class="dashboard-card" style="box-shadow: var(--shadow-4); margin-bottom: 20px; padding: 30px; border: 1px solid var(--light-gray); border-radius: var(--radius-6); text-align: left; transition: transform 0.3s ease, box-shadow 0.3s ease;">
      <div class="form-container">
        <form action="{% url 'patient_book_appointment' %}" method="post" class="form">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_doctor" class="label">Doctor:</label>
            <select name="doctor" id="id_doctor" class="input" required>
              {% for doctor in doctors %}
                <option value="{{ doctor.id }}">Dr. {{ doctor.first_name }} {{ doctor.last_name }} - {{ doctor.department.dep_name }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <label for="id_date" class="label">Date:</label>
            <input type="date" name="date" id="id_date" class="input" required>
          </div>
          <div class="form-group">
            <label for="id_time" class="label">Time:</label>
            <input type="time" name="time" id="id_time" class="input" required>
          </div>
          <div class="form-group">
            <label for="id_symptoms" class="label">Symptoms:</label>
            <textarea name="symptoms" id="id_symptoms" class="input" cols="30" rows="10" required></textarea>
          </div>
          <button type="submit" class="btn btn-primary">
            <i class="fas fa-calendar-plus"></i>
            Book Appointment
          </button>
        </form>
      </div>
    </div>
  </div>
</section>

<style>
  .dashboard-card {
    box-shadow: var(--shadow-4);
    margin-bottom: 20px;
    padding: 30px;
    border: 1px solid var(--light-gray);
    border-radius: var(--radius-6);
    text-align: left;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
  }

  .form-container {
    width: 50%;
    margin: 0 auto; /* Center the form horizontally */
    background: none;
  }

  .form-group {
    margin-bottom: 20px;
  }

  .label {
    display: block;
    font-weight: bold;
    margin-bottom: 5px;
  }

  .input {
    padding: 10px;
    width: 100%;
    border: 1px solid var(--light-gray);
    border-radius: var(--radius-6);
    font-size: 16px;
  }

  .btn-primary {
    display: inline-block;
    padding: 10px 20px;
    font-size: 16px;
    color: #fff;
    background-color: #007bff;
    border: none;
    border-radius: var(--radius-6);
    text-align: center;
    text-decoration: none;
    transition: background-color 0.3s ease;
    cursor: pointer;
  }

  .btn-primary:hover {
    background-color: #0056b3;
  }
</style>
{% endblock %}

hospitalmanagement/hospital/templates/patient/patient_confirm_delete_appointment.html
{% include 'patient/patient_navbar.html' %}

{% block content %}
<section class="section" id="delete-appointment" aria-label="delete-appointment">
  <div class="container">
    <div class="dashboard-card" style="box-shadow: var(--shadow-4); margin-bottom: 20px; padding: 30px; border: 1px solid var(--light-gray); border-radius: var(--radius-6); text-align: center; transition: transform 0.3s ease, box-shadow 0.3s ease;">
      <h2 class="h2 section-title">Confirm Deletion of Appointment</h2>
      <br>
      <p style="color: black;">Are you sure you want to delete the appointment with <b>{{ appointment.doctor.user.first_name }} {{ appointment.doctor.user.last_name }}</b> on <b>{{ appointment.date }}</b> at <b>{{ appointment.time }}</b>?</p>

      <br><br>
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <br><br>
        <a href="{% url 'patient_appointment_list' %}" class="btn btn-secondary">Cancel</a>
      </form>
    </div>
  </div>
</section>
{% endblock %}

hospitalmanagement/hospital/templates/patient/patient_dashboard.html
{% include 'patient/patient_navbar.html' %}
{% block content %}

<section class="section dashboard" id="dashboard" aria-label="dashboard" style="margin-bottom:10px; width: 100%; background-size: cover; background-repeat: no-repeat; background-position: center center;">
  <div class="container">
    <div class="dashboard-card" style="box-shadow: var(--shadow-4); margin-bottom: 20px; padding: 30px; border: 1px solid var(--light-gray); border-radius: var(--radius-6); text-align: center; transition: transform 0.3s ease, box-shadow 0.3s ease;">
      <p class="section-subtitle text-center">Patient Dashboard</p>
      <h2 class="h2 section-title text-center">Welcome, {{ user.first_name }} {{ user.last_name }}</h2>
      <br>
      <h3 class="h3 card-title" style="align-items: center; text-align: center; padding-bottom: 25px;">This is your patient dashboard.</h3>
    </div>
  </div>

  <div class="container">
    <div class="dashboard-card" style="box-shadow: var(--shadow-4); margin-bottom: 20px; padding: 30px; border: 1px solid var(--light-gray); border-radius: var(--radius-6); text-align: center; transition: transform 0.3s ease, box-shadow 0.3s ease;">
      <h3 class="h3 card-title" style="align-items: center;">Upcoming Appointment</h3>
      <ul class="list-group" style="padding-top: 10px;">
        {% for appointment in appointments %}
        <li class="list-group-item" style="text-align: left; color: var(--black);">Appointment with Dr. {{ appointment.doctor.user.first_name }} {{ appointment.doctor.user.last_name }} - ({{ appointment.doctor.department.dep_name }} Department) on {{ appointment.date }} at {{ appointment.time }}</li>
        <br>
        {% endfor %}
      </ul>
      <br>
      <a href="{% url 'patient_book_appointment' %}" class="btn btn-primary mt-3">Book a new Appointment</a>
    </div>
  </div>

  <div class="container">
    <div class="dashboard-card" style="box-shadow: var(--shadow-4); margin-bottom: 20px; padding: 30px; border: 1px solid var(--light-gray); border-radius: var(--radius-6); text-align: center; transition: transform 0.3s ease, box-shadow 0.3s ease;">
      <h3 class="h3 card-title">Your Appointments</h3>
      <ul class="appointment-list">
        {% for appointment in appointments %}
        <li class="appointment-item">
          <div class="appointment-info">
            <div><strong style="color:black;">Doctor:</strong> Dr. {{ appointment.doctor.user.first_name }} {{ appointment.doctor.user.last_name }} - ({{ appointment.doctor.department.dep_name }} Department)</div>
            <div><strong style="color:black;">Date:</strong> {{ appointment.date }}</div>
            <div><strong style="color:black;">Time:</strong> {{ appointment.time }}</div>
            <div><strong style="color:black;">Symptoms:</strong> {{ appointment.symptoms }}</div>
          </div>
        </li>
        {% empty %}
        <li>No appointments scheduled.</li>
        {% endfor %}
      </ul>
    </div>
  </div>

</section>

<style>
  .dashboard-card {
    box-shadow: var(--shadow-4);
    margin-bottom: 20px;
    padding: 30px;
    border: 1px solid var(--light-gray);
    border-radius: var(--radius-6);
    text-align: center;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
  }

  .dashboard-card:hover {
    transform: scale(1.05);
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
  }

  .card-title {
    align-items: center;
    text-align: center;
    margin-bottom: 25px;
  }

  .btn-primary {
    display: inline-block;
    padding: 10px 20px;
    font-size: 16px;
    color: #fff;
    background-color: #007bff;
    border: none;
    border-radius: var(--radius-6);
    text-align: center;
    text-decoration: none;
    transition: background-color 0.3s ease;
    margin-bottom: 10px;
  }

  .btn-primary:hover {
    background-color: #0056b3;
  }

  .list-group {
    padding-top: 10px;
  }

  .list-group-item {
    text-align: left;
  }

  .appointment-list {
    list-style: none;
    padding: 0;
    text-align: left;
  }

  .appointment-item {
    border-bottom: 1px solid #ccc;
    padding: 10px 0;
  }

  .appointment-info {
    margin-bottom: 10px;
  }

  .appointment-info div {
    margin-bottom: 5px;
  }
</style>

{% endblock %}